errors:
(particle-graph) prasannak@saalfelds-ws10:~/dev/ParticleGraphNew$ python GNN_main_forKabi.py
/home/prasannak@hhmi.org/micromamba/envs/particle-graph/lib/python3.11/site-packages/juliacall/__init__.py:60: UserWarning: torch was imported before juliacall. This may cause a segfault. To avoid this, import juliacall before importing torch. For updates, see https://github.com/pytorch/pytorch/issues/78829.
  warnings.warn(
device cpu

Generating data ...  
Traceback (most recent call last):
  File "/home/prasannak@hhmi.org/micromamba/envs/particle-graph/lib/python3.11/site-packages/scipy/io/matlab/_mio.py", line 39, in _open_file
    return open(file_like, mode), True
           ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'graphs_data/Brain.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasannak@hhmi.org/dev/ParticleGraphNew/GNN_main_forKabi.py", line 51, in <module>
    data_generate(config, device=device, visualize=True, run_vizualized=0, style='color', alpha=1, erase=True, bSave=True, step=config.simulation.n_frames // 25)
  File "/home/prasannak@hhmi.org/dev/ParticleGraphNew/src/ParticleGraph/generators/graph_data_generator.py", line 30, in data_generate
    data_generate_particle(config, visualize=visualize, run_vizualized=run_vizualized, style=style, erase=erase, step=step,
  File "/home/prasannak@hhmi.org/dev/ParticleGraphNew/src/ParticleGraph/generators/graph_data_generator.py", line 85, in data_generate_particle
    mat = scipy.io.loadmat(simulation_config.connectivity_file)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prasannak@hhmi.org/micromamba/envs/particle-graph/lib/python3.11/site-packages/scipy/io/matlab/_mio.py", line 225, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/home/prasannak@hhmi.org/micromamba/envs/particle-graph/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/prasannak@hhmi.org/micromamba/envs/particle-graph/lib/python3.11/site-packages/scipy/io/matlab/_mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prasannak@hhmi.org/micromamba/envs/particle-graph/lib/python3.11/site-packages/scipy/io/matlab/_mio.py", line 45, in _open_file
    return open(file_like, mode), True
           ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'graphs_data/Brain.mat'

--------------------------------------------------

(particle-graph) prasannak@saalfelds-ws10:~/dev/ParticleGraphNew$ python GNN_main_forKabi.py
/home/prasannak@hhmi.org/micromamba/envs/particle-graph/lib/python3.11/site-packages/juliacall/__init__.py:60: UserWarning: torch was imported before juliacall. This may cause a segfault. To avoid this, import juliacall before importing torch. For updates, see https://github.com/pytorch/pytorch/issues/78829.
  warnings.warn(
device cpu

Generating data ... description='Boids 16 different types' dataset='boids_16_256_bison_2' data_folder_name='none' simulation=SimulationConfig(dimension=2, connectivity_file='', params=[[27.6, 92.5, 48.2], [32.0, 51.8, 29.8], [23.6, 35.0, 13.5], [3.3, 76.4, 13.0], [94.0, 78.7, 30.8], [81.4, 34.6, 2.2], [3.1, 40.5, 17.0], [88.8, 7.2, 29.8], [32.7, 76.8, 26.1], [14.5, 56.8, 27.6], [63.3, 99.9, 13.9], [32.5, 25.2, 24.4], [97.6, 56.5, 12.1], [62.2, 9.1, 28.3], [76.4, 52.9, 32.0], [48.1, 54.4, 30.7]], cell_cycle_length=[-1], cell_death_rate=[-1], min_radius=0.001, max_radius=0.04, angular_sigma=0, angular_Bernouilli=[-1], max_edges=1000000.0, diffusion_coefficients=None, n_particles=1792, n_particles_max=20000, n_particle_types=16, n_interactions=16, non_discrete_level=0, n_nodes=10000, n_node_types=1, pos_rate=None, neg_rate=None, has_cell_division=False, n_frames=2048, sigma=0.005, delta_t=2.0, dpos_init=0.0005, boundary='periodic', node_type_map='pattern_Null.tif', node_value_map='video_bisons_2048_2.tif', node_diffusion_map='pattern_Null.tif', node_proliferation_map='pattern_Null.tif', beta=None, start_frame=0) graph_model=GraphModelConfig(particle_model_name='PDE_ParticleField_B', mesh_model_name='', signal_model_name='', prediction='2nd_derivative', input_size=9, output_size=2, hidden_dim=256, n_mp_layers=5, aggr_type='mean', mesh_aggr_type='add', embedding_dim=2, update_type='none', input_size_update=3, n_layers_update=3, hidden_dim_update=64, output_size_update=1, input_size_nnr=3, n_layers_nnr=5, hidden_dim_nnr=128, output_size_nnr=1, field_method='tensor', division_predictor_input_size=3, division_predictor_hidden_dim=64, division_predictor_n_layers=3, division_predictor_output_size=1, field_type='siren_with_time') plotting=PlottingConfig(colormap='tab20', arrow_length=5, marker_size=100, ylim=[-0.1, 0.1]) training=TrainingConfig(n_epochs=0, batch_size=8, small_init_batch_size=True, large_range=False, has_no_tracking=False, n_runs=2, seed=40, clamp=0, pred_limit=10000000000.0, sparsity='none', sparsity_freq=5, particle_dropout=0, n_ghosts=0, ghost_method='none', ghost_logvar=-12, fix_cluster_embedding=True, loss_weight=False, learning_rate_start=0.001, learning_rate_end=0.0005, learning_rate_embedding_start=0.001, learning_rate_embedding_end=0.001, coeff_loss1=1, coeff_loss2=1, coeff_loss3=1, noise_level=0.0, data_augmentation=True, data_augmentation_loop=100, recursive_loop=0, sub_batches=1, sequence=['to track', 'to cell'], cluster_method='distance_plot', cluster_distance_threshold=0.01, cluster_connectivity='single', device='auto') PDE_ParticleField_B 
Traceback (most recent call last):
  File "/home/prasannak@hhmi.org/dev/ParticleGraphNew/GNN_main_forKabi.py", line 51, in <module>
    data_generate(config, device=device, visualize=True, run_vizualized=0, style='color', alpha=1, erase=True, bSave=True, step=config.simulation.n_frames // 25)
  File "/home/prasannak@hhmi.org/dev/ParticleGraphNew/src/ParticleGraph/generators/graph_data_generator.py", line 18, in data_generate
    data_generate_particle_field(config, visualize=visualize, run_vizualized=run_vizualized, style=style, erase=False, step=step,
  File "/home/prasannak@hhmi.org/dev/ParticleGraphNew/src/ParticleGraph/generators/graph_data_generator.py", line 914, in data_generate_particle_field
    X1_mesh, V1_mesh, T1_mesh, H1_mesh, A1_mesh, N1_mesh, mesh_data = init_mesh(config, model_mesh=model_f_f, device=device)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prasannak@hhmi.org/dev/ParticleGraphNew/src/ParticleGraph/generators/utils.py", line 373, in init_mesh
    i0 = imread(f'graphs_data/{node_value_map}')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prasannak@hhmi.org/micromamba/envs/particle-graph/lib/python3.11/site-packages/tifffile/tifffile.py", line 1230, in imread
    with TiffFile(
         ^^^^^^^^^
  File "/home/prasannak@hhmi.org/micromamba/envs/particle-graph/lib/python3.11/site-packages/tifffile/tifffile.py", line 4240, in __init__
    fh = FileHandle(file, mode=mode, name=name, offset=offset, size=size)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prasannak@hhmi.org/micromamba/envs/particle-graph/lib/python3.11/site-packages/tifffile/tifffile.py", line 14555, in __init__
    self.open()
  File "/home/prasannak@hhmi.org/micromamba/envs/particle-graph/lib/python3.11/site-packages/tifffile/tifffile.py", line 14574, in open
    self._fh = open(
               ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/prasannak@hhmi.org/dev/ParticleGraphNew/graphs_data/video_bisons_2048_2.tif'

---------------------------------

(particle-graph) prasannak@saalfelds-ws10:~/dev/ParticleGraphNew$ python GNN_main_forKabi.py
/home/prasannak@hhmi.org/micromamba/envs/particle-graph/lib/python3.11/site-packages/juliacall/__init__.py:60: UserWarning: torch was imported before juliacall. This may cause a segfault. To avoid this, import juliacall before importing torch. For updates, see https://github.com/pytorch/pytorch/issues/78829.
  warnings.warn(
device cpu

Generating data ... description='attraction-repulsion with 3 types particles + field with strong coupling' dataset='arbitrary_3_field_video_bison' data_folder_name='none' simulation=SimulationConfig(dimension=2, connectivity_file='', params=[[1.6233, 1.0413, 1.6012, 1.5615], [1.7667, 1.8308, 1.0855, 1.9055], [1.7226, 1.785, 1.0584, 1.8579]], cell_cycle_length=[-1], cell_death_rate=[-1], min_radius=0.0, max_radius=0.075, angular_sigma=0, angular_Bernouilli=[-1], max_edges=1000000.0, diffusion_coefficients=[[0.0]], n_particles=4800, n_particles_max=20000, n_particle_types=3, n_interactions=3, non_discrete_level=0, n_nodes=10000, n_node_types=1, pos_rate=[[0.0]], neg_rate=[[0.0]], has_cell_division=False, n_frames=256, sigma=0.005, delta_t=0.1, dpos_init=0.0, boundary='periodic', node_type_map='pattern_Null.tif', node_value_map='video_bisons.tif', node_diffusion_map='pattern_Null.tif', node_proliferation_map='pattern_Null.tif', beta=None, start_frame=0) graph_model=GraphModelConfig(particle_model_name='PDE_ParticleField_A', mesh_model_name='', signal_model_name='', prediction='first_derivative', input_size=5, output_size=2, hidden_dim=128, n_mp_layers=5, aggr_type='mean', mesh_aggr_type='add', embedding_dim=2, update_type='none', input_size_update=3, n_layers_update=3, hidden_dim_update=64, output_size_update=1, input_size_nnr=3, n_layers_nnr=5, hidden_dim_nnr=128, output_size_nnr=1, field_method='tensor', division_predictor_input_size=3, division_predictor_hidden_dim=64, division_predictor_n_layers=3, division_predictor_output_size=1, field_type='siren_with_time') plotting=PlottingConfig(colormap='tab10', arrow_length=2, marker_size=100, ylim=[-0.1, 0.1]) training=TrainingConfig(n_epochs=20, batch_size=8, small_init_batch_size=False, large_range=False, has_no_tracking=False, n_runs=2, seed=40, clamp=0, pred_limit=10000000000.0, sparsity='none', sparsity_freq=5, particle_dropout=0, n_ghosts=0, ghost_method='none', ghost_logvar=-12, fix_cluster_embedding=True, loss_weight=False, learning_rate_start=0.001, learning_rate_end=0.0005, learning_rate_embedding_start=0.001, learning_rate_embedding_end=0.001, coeff_loss1=1, coeff_loss2=1, coeff_loss3=1, noise_level=0, data_augmentation=True, data_augmentation_loop=200, recursive_loop=0, sub_batches=1, sequence=['to track', 'to cell'], cluster_method='distance_plot', cluster_distance_threshold=0.01, cluster_connectivity='single', device='auto') PDE_ParticleField_A 
Traceback (most recent call last):
  File "/home/prasannak@hhmi.org/dev/ParticleGraphNew/GNN_main_forKabi.py", line 51, in <module>
    data_generate(config, device=device, visualize=True, run_vizualized=0, style='color', alpha=1, erase=True, bSave=True, step=config.simulation.n_frames // 25)
  File "/home/prasannak@hhmi.org/dev/ParticleGraphNew/src/ParticleGraph/generators/graph_data_generator.py", line 18, in data_generate
    data_generate_particle_field(config, visualize=visualize, run_vizualized=run_vizualized, style=style, erase=False, step=step,
  File "/home/prasannak@hhmi.org/dev/ParticleGraphNew/src/ParticleGraph/generators/graph_data_generator.py", line 874, in data_generate_particle_field
    model_p_p, bc_pos, bc_dpos = choose_model(config, device=device)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prasannak@hhmi.org/dev/ParticleGraphNew/src/ParticleGraph/generators/utils.py", line 80, in choose_model
    p[n] = torch.tensor(params[n])
    ~^^^
RuntimeError: The expanded size of the tensor (3) must match the existing size (4) at non-singleton dimension 0.  Target sizes: [3].  Tensor sizes: [4]


